config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :todos
  get 'top/index'

  root "top#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:date, :title, :body, :deadline)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:date, :title, :body, :deadline)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @todos = Todo.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo007</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Body</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.date %></td>
        <td><%= list.title %></td>
        <td><%= list.body %></td>
        <td><%= list.deadline %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @list.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @list.body %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @list.deadline %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :登録日 %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :詳細 %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :期限 %>
    <%= form.date_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<head>
	<!-- ビューポートの設定 -->
	<meta name="viewport" content="width=device-width,initial-scale=1">

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <link href='https://fonts.googleapis.com/css?family=Comfortaa:400,700' rel='stylesheet' type='text/css'>

</head>

<div id="header">
  <div class="logo">
    <%= link_to 'TAKUMI', root_path %>
  </div>
  <nav>
    <!-- <form class="search" action="search.php">
      <input name="q" placeholder="Search..." type="search">
    </form> -->
    <ul>
      <li>
        <%= link_to 'TOP', root_path %>
      </li>
      <li>
        <%= link_to '新規タスク登録', new_todo_path %>
      </li>
      <li>
        <%= link_to 'タスク一覧', todos_path %>
      </li>
    </ul>
  </nav>
</div>

<script>
$('#header').prepend('<div id="menu-icon"><span class="first"></span><span class="second"></span><span class="third"></span></div>');

$("#menu-icon").on("click", function(){
  $("nav").slideToggle();
  $(this).toggleClass("active");
});
</script>

<p id="notice"><%= notice %></p>

<CENTER>

<br>
<h1>タスク一覧</h1>
<section>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>詳細</th>
      <th>期限</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
    <tr>
      <th><%= todo.title %></th>
      <td><%= todo.body %></td>
      <td><%= todo.deadline %></td>
      <td><%= link_to '詳細', todo %></td>
      <td><%= link_to '編集', edit_todo_path(todo) %></td>
      <td><%= link_to '削除', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
      <% end %>
   </tbody>
</table>
</section>

<br>

<!-- <table>
  <thead>
    <tr><th>登録日</th><th>タイトル</th><th>詳細</th><th>期限</th><th colspan="3"></th>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.date %></td>
        <td><%= todo.title %></td>
        <td><%= todo.body %></td>
        <td><%= todo.deadline %></td>
        <td><%= link_to '詳細', todo %></td>
        <td><%= link_to '編集', edit_todo_path(todo) %></td>
        <td><%= link_to '削除', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody> -->
  <!-- <tbody>
    <tr><td>〇</td><td>〇</td><td>〇</td><td>〇</td><td>〇</td>
  </tbody> -->
<!-- </table>
<br> -->
<!-- <div class="outer">
<table>
  <thead>
    <tr>
      <th>登録日</th>
      <th>タイトル</th>
      <th>詳細</th>
      <th>期限</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.date %></td>
        <td><%= todo.title %></td>
        <td><%= todo.body %></td>
        <td><%= todo.deadline %></td>
        <td><%= link_to '詳細', todo %></td>
        <td><%= link_to '編集', edit_todo_path(todo) %></td>
        <td><%= link_to '削除', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div> -->

</CENTER>

<br>

<%= link_to '新規タスク登録', new_todo_path %>

app/views/todos/new.html.erb
<head>
	<!-- ビューポートの設定 -->
	<meta name="viewport" content="width=device-width,initial-scale=1">

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>

<div id="header">
  <div class="logo">
    <%= link_to 'TAKUMI', root_path %>
  </div>
  <nav>
    <!-- <form class="search" action="search.php">
      <input name="q" placeholder="Search..." type="search">
    </form> -->
    <ul>
      <li>
        <%= link_to 'TOP', root_path %>
      </li>
      <li>
        <%= link_to '新規タスク登録', new_todo_path %>
      </li>
      <li>
        <%= link_to 'タスク一覧', todos_path %>
      </li>
    </ul>
  </nav>
</div>

<script>
$('#header').prepend('<div id="menu-icon"><span class="first"></span><span class="second"></span><span class="third"></span></div>');

$("#menu-icon").on("click", function(){
  $("nav").slideToggle();
  $(this).toggleClass("active");
});
</script>

<h1>新規タスク登録</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<head>
	<!-- ビューポートの設定 -->
	<meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Bootstrap CSS -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->


  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>

<div id="header">
  <div class="logo">
    <%= link_to 'TAKUMI', root_path %>
  </div>
  <nav>
    <!-- <form class="search" action="search.php">
      <input name="q" placeholder="Search..." type="search">
    </form> -->
    <ul>
      <li>
        <%= link_to 'TOP', root_path %>
      </li>
      <li>
        <%= link_to '新規タスク登録', new_todo_path %>
      </li>
      <li>
        <%= link_to 'タスク一覧', todos_path %>
      </li>
    </ul>
  </nav>
</div>

<script>
$('#header').prepend('<div id="menu-icon"><span class="first"></span><span class="second"></span><span class="third"></span></div>');

$("#menu-icon").on("click", function(){
  $("nav").slideToggle();
  $(this).toggleClass("active");
});
</script>


<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @todo.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @todo.body %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @todo.deadline %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/top/index.html.erb
<head>
	<!-- ビューポートの設定 -->
	<meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Bootstrap CSS -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->


  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>

<div id="header">
  <div class="logo">
    <%= link_to 'TAKUMI', root_path %>
  </div>
  <nav>
    <!-- <form class="search" action="search.php">
      <input name="q" placeholder="Search..." type="search">
    </form> -->
    <ul>
      <li>
        <%= link_to 'TOP', root_path %>
      </li>
      <li>
        <%= link_to '新規タスク登録', new_todo_path %>
      </li>
      <li>
        <%= link_to 'タスク一覧', todos_path %>
      </li>
    </ul>
  </nav>
</div>

<script>
$('#header').prepend('<div id="menu-icon"><span class="first"></span><span class="second"></span><span class="third"></span></div>');

$("#menu-icon").on("click", function(){
  $("nav").slideToggle();
  $(this).toggleClass("active");
});
</script>


<div class="top01">
  <h1>タスク管理アプリ</h1>
</div>

<div class="box2">
    <p>現在のタスク数<br><%= @todos.count %></p>
</div>

<div class="top02">
<a href="todos/new" class="square_btn">新規タスク登録</a>
<a href="todos" class="square_btn">タスク一覧</a>
</div>

<CENTER>

  <!-- <div class="row">
    <div class="col-sm-9"> 左コンテンツエリア </div>
    <div class="col-sm-3"> 右コンテンツエリア </div>
  </div> -->


<div class="accbox">
  <!--ラベル1-->
    <label for="label1">タスク管理アプリとは</label>
    <input type="checkbox" id="label1" class="cssacc" />
    <div class="accshow">
      <!--ここに隠す中身-->
      <p>
        ここにアプリの説明
      </p>
    </div>
    <!--//ラベル1-->
  <!--ラベル2-->
    <label for="label2">新規タスク登録の方法</label>
    <input type="checkbox" id="label2" class="cssacc" />
    <div class="accshow">
      <!--ここに隠す中身-->
      <p>
        こんにちは2
      </p>
    </div>
    <!--//ラベル2-->
  <!--ラベル3-->
    <label for="label3">タスク一覧の確認について</label>
    <input type="checkbox" id="label3" class="cssacc" />
    <div class="accshow">
      <!--ここに隠す中身-->
      <p>
        こんにちは3
      </p>
    </div>
    <!--//ラベル3-->
  <!--ラベル4-->
    <label for="label4">よくある質問</label>
    <input type="checkbox" id="label4" class="cssacc" />
    <div class="accshow">
      <!--ここに隠す中身-->
      <p>
        こんにちは4
      </p>
    </div>
    <!--//ラベル4-->
</div><!--//.accbox-->

<div id="social-platforms">

<a class="btn btn-icon btn-facebook" href="#"><i class="fa fa-facebook"></i><span>Facebook</span></a>
<a class="btn btn-icon btn-twitter" href="#"><i class="fa fa-twitter"></i><span>Twitter</span></a>
</div>

</CENTER>